[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'
exclude = [
  "\.eggs",
  "\.git",
  "\.mypy_cache",
  "\.pytest_cache",
  "\.venv",
  "node_modules",
]

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["backend"]

[tool.ruff]
line-length = 100
target-version = "py312"
src = ["backend"]
exclude = [".venv", "node_modules", "dist", "build"]
lint.select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
lint.ignore = [
  "E203",  # whitespace before ':' (black compatible)
]
